name: lms_alpha
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  http: ^1.2.2
  intl: ^0.19.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_gen_runner: ^5.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Fugaz One
      fonts:
        - asset: assets/fonts/FugazOne-Regular.ttf
    - family: Duru Sans
      fonts:
        - asset: assets/fonts/DuruSans-Regular.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf  